apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istiod
  namespace: istio-system
spec:
  interval: 5m
  releaseName: istiod
  chart:
    spec:
      chart: istiod
      version: "1.24.1"
      sourceRef:
        kind: HelmRepository
        name: fe-stack
        namespace: flux-system
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: istiod-hr-values
      valuesKey: values.yaml
    
