global:
  # Used to locate istiod.
  istioNamespace: istio-system
  defaultResources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 200m
    memory: 256Mi

  hub: festack.azurecr.io/istio
  tag: "1.24.1"
  imagePullPolicy: IfNotPresent
  imagePullSecrets:
    - acr-fes

  omitSidecarInjectorConfigMap: true

  # meshConfig defines runtime configuration of components, including Istiod and istio-agent behavior
  # See https://istio.io/docs/reference/config/istio.mesh.v1alpha1/ for all available options
meshConfig:
    enablePrometheusMerge: true
    extensionProviders:
      - name: "oidc-proxy-provider-fes"
        envoyExtAuthzHttp:
          service: "fe-stack-oidc-proxy.fes.svc.cluster.local"
          port: "8280"
          includeRequestHeadersInCheck: ["c*", "x*", "s*", "t*", "h*", "r*", "api_key"]
          headersToUpstreamOnAllow: ["cookie", "set-cookie*", "x-oidc-proxy*"]
      - name: "oidc-proxy-provider-qa"
        envoyExtAuthzHttp:
          service: "fe-stack-oidc-proxy.qa.svc.cluster.local"
          port: "8280"
          includeRequestHeadersInCheck: ["c*", "x*", "s*", "t*", "h*", "r*", "api_key"]
          headersToUpstreamOnAllow: ["cookie", "set-cookie*", "x-oidc-proxy*"] 
      - name: "oidc-proxy-provider-performance"
        envoyExtAuthzHttp:
          service: "fe-stack-oidc-proxy.performance.svc.cluster.local"
          port: "8280"
          includeRequestHeadersInCheck: ["c*", "x*", "s*", "t*", "h*", "r*", "api_key"]
          headersToUpstreamOnAllow: ["cookie", "set-cookie*", "x-oidc-proxy*"]           
    accessLogFormat: |
      {               
        "host": "%REQ(HOST)%",
        "hostname": "%HOSTNAME%",
        "authority": "%REQ(:AUTHORITY)%",                                     
        "start_time": "%START_TIME%",
        "bytes_received": "%BYTES_RECEIVED%",                                    
        "bytes_sent": "%BYTES_SENT%",                                           
        "downstream_local_address": "%DOWNSTREAM_LOCAL_ADDRESS%",                                    
        "downstream_remote_address": "%DOWNSTREAM_REMOTE_ADDRESS%",                                    
        "duration": "%DURATION%",                                    
        "istio_policy_status": "%DYNAMIC_METADATA(istio.mixer:status)%",                                    
        "method": "%REQ(:METHOD)%",                                    
        "path": "%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%",         
        "protocol": "%PROTOCOL%",
        "trace_id": "%REQ(X-B3-TRACEID)%",
        "span_id": "%REQ(X-B3-SPANID)%",                                       
        "request_id": "%REQ(X-REQUEST-ID)%",                                    
        "requested_server_name": "%REQUESTED_SERVER_NAME%",                                    
        "response_code": "%RESPONSE_CODE%",                                    
        "response_flags": "%RESPONSE_FLAGS%",
        "response_code_details": "%RESPONSE_CODE_DETAILS%", 
        "connection_termination_details": "%CONNECTION_TERMINATION_DETAILS%",                                
        "route_name": "%ROUTE_NAME%",                                    
        "upstream_cluster": "%UPSTREAM_CLUSTER%",                                    
        "upstream_host": "%UPSTREAM_HOST%",                                    
        "upstream_local_address": "%UPSTREAM_LOCAL_ADDRESS%",                                    
        "upstream_service_time": "%RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)%",                                    
        "upstream_transport_failure_reason": "%UPSTREAM_TRANSPORT_FAILURE_REASON%",                                    
        "user_agent": "%REQ(USER-AGENT)%",                                    
        "x_forwarded_for": "%REQ(X-FORWARDED-FOR)%",
        "company_id": "%DYNAMIC_METADATA(userInfo:FAREYE_CMP_ID)%",
        "emp_code": "%DYNAMIC_METADATA(userInfo:FAREYE_EMP_CODE)%"
      }
    accessLogFile: /dev/stdout
    enableAutoMtls: false
    accessLogEncoding: JSON
    enableTracing: true
    h2UpgradePolicy: DO_NOT_UPGRADE
    defaultConfig:
      gatewayTopology:
        numTrustedProxies: 2
      tracing:
        sampling: 100
        zipkin:
          address: tempo-distributed-distributor.monitoring:9411
# meshConfig:
#   extensionProviders:
#     - name: "oidc-proxy-provider-fes"
#       envoyExtAuthzHttp:
#         service: "fe-stack-oidc-proxy.fes.svc.cluster.local"
#         port: "8280"
#         includeRequestHeadersInCheck: ["c*", "x*", "s*", "t*", "h*", "r*", "api_key"]
#         headersToUpstreamOnAllow: ["cookie", "set-cookie*", "x-oidc-proxy*"]  
  
