apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-ingress-gateway
  namespace: istio-system
spec:
  profile: empty # Do not install CRDs or the control plane
  hub: fareye.azurecr.io/istio
  tag: "1.15.3"
  values:
    global:
      imagePullSecrets:
        - acr-credential
  components:
    ingressGateways:
    - name: istio-ingressgateway
      namespace: istio-system
      enabled: true
      label:
        istio: istio-ingressgateway
      k8s:
        service:
          externalTrafficPolicy: Local
          type: NodePort
        serviceAnnotations:
          service.beta.kubernetes.io/azure-load-balancer-tcp-idle-timeout: "5"
          alb.ingress.kubernetes.io/healthcheck-path: /healthz/ready
          alb.ingress.kubernetes.io/healthcheck-port: "status-port"
        hpaSpec:
          minReplicas: "1"
          maxReplicas: "20"
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 200m
            memory: 256Mi
  meshConfig:
    accessLogFormat: |
      {               
                        "authority": "%REQ(:AUTHORITY)%",                                     
                        "start_time": "%START_TIME%",
                        "bytes_received": "%BYTES_RECEIVED%",                                    
                        "bytes_sent": "%BYTES_SENT%",                                           
                        "downstream_local_address": "%DOWNSTREAM_LOCAL_ADDRESS%",                                    
                        "downstream_remote_address": "%DOWNSTREAM_REMOTE_ADDRESS%",                                    
                        "duration": "%DURATION%",                                    
                        "istio_policy_status": "%DYNAMIC_METADATA(istio.mixer:status)%",                                    
                        "method": "%REQ(:METHOD)%",                                    
                        "path": "%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%",         
                        "protocol": "%PROTOCOL%",
                        "trace_id": "%REQ(X-B3-TRACEID)%",
                        "span_id": "%REQ(X-B3-SPANID)%",                                       
                        "request_id": "%REQ(X-REQUEST-ID)%",                                    
                        "requested_server_name": "%REQUESTED_SERVER_NAME%",                                    
                        "response_code": "%RESPONSE_CODE%",                                    
                        "response_flags": "%RESPONSE_FLAGS%",
                        "response_code_details": "%RESPONSE_CODE_DETAILS%", 
                        "connection_termination_details": "%CONNECTION_TERMINATION_DETAILS%",                                
                        "route_name": "%ROUTE_NAME%",                                    
                        "upstream_cluster": "%UPSTREAM_CLUSTER%",                                    
                        "upstream_host": "%UPSTREAM_HOST%",                                    
                        "upstream_local_address": "%UPSTREAM_LOCAL_ADDRESS%",                                    
                        "upstream_service_time": "%RESP(X-ENVOY-UPSTREAM-SERVICE-TIME)%",                                    
                        "upstream_transport_failure_reason": "%UPSTREAM_TRANSPORT_FAILURE_REASON%",                                    
                        "user_agent": "%REQ(USER-AGENT)%",                                    
                        "x_forwarded_for": "%REQ(X-FORWARDED-FOR)%",
                        "company_id": "%DYNAMIC_METADATA(userInfo:FAREYE_CMP_ID)%",
                        "emp_code": "%DYNAMIC_METADATA(userInfo:FAREYE_EMP_CODE)%"
      }
    accessLogFile: /dev/stdout
    accessLogEncoding: JSON
    enableTracing: true
    defaultConfig:
      gatewayTopology:
        numTrustedProxies: "2"
      tracing:
        sampling: "100"
        zipkin:
          address: tempo-distributed-distributor.monitoring:9411
