apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-operator
  namespace: istio-system
spec:
  releaseName: istio-operator
  chart:
    spec:
      chart: './manifests/charts/istio-operator/'
      sourceRef:
        kind: GitRepository
        name: istio-system
        namespace: istio-system
      version: "1.15.3"
  interval: 10m
  install:
    remediation:
      retries: 3
  values:
    operatorNamespace: istio-operator
    watchedNamespaces: istio-system,fes
    hub: fareye.azurecr.io/istio
    tag: "1.15.3"
    imagePullSecrets:
     - name: acr-credential
