apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- istio-operator
#- image-secret-system-ns.yaml
- crd
- source.yaml
#- git-credential-sealed.yaml
patchesStrategicMerge:
- istio-operator-patch.yaml
- istio-system-patch.yaml
- istio-gateway-patch.yaml
