apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fes
generatorOptions:
  disableNameSuffixHash: true
resources:
- release.yaml

configMapGenerator:
- name: fes-istio-hr-values
  files:
  - values.yaml
