apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: fes-istio
  namespace: fes
spec:
  interval: 5m
  releaseName: fes-istio
  chart:
    spec:
      chart: fes-istio
      version: v1.0.0
      sourceRef:
        kind: HelmRepository
        name: fe-stack
        namespace: flux-system
  install:
    remediation:
      retries: 3
  valuesFrom:
  - kind: ConfigMap
    name: fes-istio-hr-values
    valuesKey: values.yaml
