apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-system
generatorOptions:
  disableNameSuffixHash: true      
resources:
  - release.yaml
  
configMapGenerator:
  - name: istio-base-hr-values
    files:
      - values.yaml