apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-web-view
  namespace: fes
spec:
  releaseName: kube-web-view
  chart:
    spec:
      chart: kube-web-view
      version: "0.4.0"
      sourceRef:
        kind: HelmRepository
        name: fe-stack
        namespace: flux-system 
  interval: 10m
  install:
    remediation:
      retries: 3

  values:
    extraArgs:
    - --port=8080
    # uncomment the following line to enable pod logs
    # (disabled by default as they might consider sensitive information)
    - "--show-container-logs"

    image:
      repository: festack.azurecr.io/kube-web-view
      pullPolicy: IfNotPresent
      tag: "23.8.0"
    imagePullSecrets:
      - name: acr-fes

    
