apiVersion: v1
kind: Pod
metadata:
  name: minimal-pod
  namespace: default
spec:
  containers:
    - name: minimal-container
      image: busybox  # Minimal image
      command: ["sh", "-c", "echo Hello, Kubernetes! && sleep 3600"]
