apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: fe-stack
  namespace: flux-system
spec:
  interval: 1m
  url: https://chart.fareye.io
  secretRef:
    name: basic-auth
